### ISSUE TITLE
High quality plugin

### ISSUE THREAD

**Issue by zhenyangze** [leafOfTree/vim-project#1]
This is my expected project management plug-in, although not many people star it now.

There are several questions for feedback:

1. If two projects have the same name but different paths, there will be problems when switching projects

2. If  set vim_project_autoload_on_start When you open the file, there will be a problem with the color. Press enter again and it will be OK

3. Open an empty directory without loading the project

**Comment by leafOfTree** [comment]
Hey, thank you for the feedback. I'll look into them and see what I can do. I'll let you know if there is any update.

**Comment by leafOfTree** [comment]
Hi, there. 
I just updated the plugin with bug fixes and new features. Please try and see how it works.

**Comment by leafOfTree** [comment]
Forgot to mention that there are many breaking changes, so it's better to try it as a new plugin with reference to the README.
