### ISSUE TITLE
Add project alias to distinguish projects with the same name but in different path

### ISSUE THREAD

**Issue by bigshans** [leafOfTree/vim-project#10]
I have two projects with the same name located in the different path. Now when I call `Project` to add a project, it will overwrites the previous one. The feature of alias will help to slove this problem.

**Comment by leafOfTree** [comment]
Thanks.
This is a bug introduced by a8fbb53. Projects with the same name on different paths are actually added. But they are hidden if they have the same `name` to the current project.

I've changed `name` to `fullpath` to fix this issue by 50a95c7. Please update and try.

**Comment by bigshans** [comment]
The bug is fixed, thanks!
