### ISSUE TITLE
No directory

### ISSUE THREAD

**Issue by zhenyangze** [leafOfTree/vim-project#2]
if some directory is trashed, it will report `[vim-project] No directory` when vim starting, can plugin disable that info or remove the config of the trashed directory?

**Comment by leafOfTree** [comment]
Sorry for the late response. Actually, I've rewritten it a lot recently for ease of use. However, it will introduce some breaking changes. I'll update it later when ready.

Currently, you can find auto-added directory config at `~/.vim/vim-project-config/_add.vim`. You can remove those that have been trashed.

**Comment by leafOfTree** [comment]
Sorry for the late response. Actually, I've rewritten it a lot recently for ease of use. I'll update it later when ready.

Currently, you can find directory config at `~/.vim/vim-project-config/_add.vim`. You can remove those that have been trashed.

**Comment by leafOfTree** [comment]
This should be fixed with the latest version. No messages now when vim starts.
