### ISSUE TITLE
ProjectSearchFiles error

### ISSUE THREAD

**Issue by jinweizhiyuan** [leafOfTree/vim-project#3]
input `:ProjectSearchFiles` and and enter return，then input file name, result is nothin，and then enter, an error is happen
![1](https://user-images.githubusercontent.com/7023430/178904928-5a4a8f5d-19e3-4318-a84d-71cfc21d637c.png)
d
![2](https://user-images.githubusercontent.com/7023430/178904956-afddc6d8-df2f-4091-974b-99917f4aff5e.png)

**Comment by leafOfTree** [comment]
Hi, thanks for your feedback. 

I've fixed the error. It will show a message on opening an empty target. https://github.com/leafOfTree/vim-project/commit/4cc1c69e91387e0c4df19438a36f0fbba2a1284e

![Screen Shot 2022-07-14 at 13 57 59](https://user-images.githubusercontent.com/13349592/178910553-5788878c-260c-4ec9-81e3-7c834b36115d.png)
