### ISSUE TITLE
ProjectSearchFiles using the configuration search_exclude don't work

### ISSUE THREAD

**Issue by jinweizhiyuan** [leafOfTree/vim-project#4]
Seach file by name in project , search_exclude(['.git', 'node_modules', '.DS_Store'])  has no effect, it still search these directories.
![1](https://user-images.githubusercontent.com/7023430/179440447-f647384a-b43d-416e-b761-f8d7cad8ef51.png)
![2](https://user-images.githubusercontent.com/7023430/179440482-e1a273fc-7768-45c1-a0dc-4b469e05cc6c.png)

**Comment by leafOfTree** [comment]
Hi, can you tell me which search tool you're using?
If you're not sure, you can check it by `:ProjectInfo`

![Screen Shot 2022-07-18 at 14 26 27](https://user-images.githubusercontent.com/13349592/179455387-38d1ced3-c381-42f6-a0e0-32c1b1ca0d63.png)

**Comment by jinweizhiyuan** [comment]
> Hi, can you tell me which search tool you're using? If you're not sure, you can check it by `:ProjectInfo`
> 
> ![Screen Shot 2022-07-18 at 14 26 27](https://user-images.githubusercontent.com/13349592/179455387-38d1ced3-c381-42f6-a0e0-32c1b1ca0d63.png)
![1](https://user-images.githubusercontent.com/7023430/179455831-6ef1681b-76bf-4d4b-b29a-32ddef07ea7d.png)

**Comment by leafOfTree** [comment]
A recent change with single quotes seems to cause the issue on Windows. 

It should be fixed now by using double quotes: https://github.com/leafOfTree/vim-project/commit/74729fd7e394aa4a4438e3a8098c6520735f195b

**Comment by leafOfTree** [comment]
Hi there, since then I've fixed a few search file display issues, as well as reduced options to

- `include`
- `exclude`

These are base options. The final result is like `exclude (global + local)` + `search_exclude(global + local)`.

Mostly, I feel that we only need to adjust `exclude`. No need to set search and find_in_files separately. Hope that's helpful.
