### ISSUE TITLE
Add current path  to Project Manger 

### ISSUE THREAD

**Issue by ooing** [leafOfTree/vim-project#6]
Do not enter the full path the path， may be too long
can add  new command ?

**Comment by leafOfTree** [comment]
Good point, thanks. 
The current path is also added to `project_base` with https://github.com/leafOfTree/vim-project/commit/83a57a2dc60a9aed910921b18f471e207f881cfa. Now you can add the project under the current path by its folder name directly.

**Comment by ooing** [comment]
I ues plug
```  vim
Plug 'leafOfTree/vim-project',{'on':['Project','ProjectList','ProjectSearchFiles','ProjectFindInFiles']}
```
Unable to take effect for the first time

**Comment by leafOfTree** [comment]
Please update `vim-project` to the latest via your plugin manager, as I just added some changes to support `../` in path.

To clarify, the current path is also called the working directory (the output of `:pwd`). It can be changed by `:cd`. Also see the option `autochdir`. 

> It becomes a bit confusing when opening a directory other than a file. It depends on which directory browse plugin (netrw, nerdtree, fern, etc.) you use, so remember to check it via `:pwd`.

For example, with the file structure
```
- tmp/
   |- abc/
   |- package.json
```

Open `tmp` or `package.json`, make sure `:pwd` is `/path/to/tmp`, then I can run `:Project abc` to add the project `abc`. 

I also can run `:Project ../tmp` to add the project `tmp`. Another way is to call `:cd ..`, then I can just run `:Project tmp`.

**Comment by ooing** [comment]
@leafOfTree    thanks
